### ISSUE TITLE
Refactor: update pre-commit/CI

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/autoemulate#364]
We might consider updating/extending the pre-commit and CI with suggestions such as those in [python-project-template](https://github.com/alan-turing-institute/python-project-template/tree/main?tab=readme-ov-file#formatting-and-checking-your-code):
- ruff (drop-in replacement for black + provides a fast linter)
- mypy/pyright (as we integrate type hints)
- other potential pre-commit / CI

**Comment by EdwinB12** [comment]
RUUUFFFF

**Comment by EdwinB12** [comment]
Not sure the above pre-commit reorders imports though, may want to add that

**Comment by EdwinB12** [comment]
```
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.7
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
     - id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]
```

_think_ this might do it. Taken from this issue: https://github.com/astral-sh/ruff-pre-commit/issues/64
